### ISSUE TITLE
Updating the config file inputs to accept dynamically loaded classes within the selene package

### ISSUE THREAD

**Issue by kathyxchen** [FunctionLab/selene#20]
Currently, I think this issue is only applicable to the `sampler` module. We may eventually extend the same idea to other modules in selene. 

A user should be able to choose what kind of data sampler they want to use when training their model. Each of these samplers has very different input requirements. For example, an IntervalsSampler specific config file would have a lot more parameters compared to a MatFilesSampler config file. In the YAML file, a user should specify the `type` of sampler they want to use. The value of `type` should be the class name of the sampler. The remaining parameters could be specified under a `parameter` key:

```
type: IntervalsSampler
parameters:
    genome: <path to indexed genome fasta file>
    query_feature_data: <path to tabix-indexed features .bed.gz file>
    ...
```
